NUM_NODES=2
NUM_GPUS_PER_NODE=4
OMP_NUM_THREADS=1
MASTER_ADDR=g0105
NODE_RANK=1
Total GPUS: 8
Traceback (most recent call last):
  File "./baseline-train-translation.py", line 39, in <module>
    train_data = datasets.load_dataset("wmt14", "de-en", split="train[:50%]")
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/load.py", line 1734, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/load.py", line 1492, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/load.py", line 1216, in dataset_module_factory
    raise e1 from None
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/load.py", line 1187, in dataset_module_factory
    return HubDatasetModuleFactoryWithScript(
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/load.py", line 902, in get_module
    local_path = self.download_loading_script()
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/load.py", line 870, in download_loading_script
    return cached_path(file_path, download_config=download_config)
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/utils/file_utils.py", line 211, in cached_path
    output_path = ExtractManager(cache_dir=download_config.cache_dir).extract(
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/utils/extract.py", line 42, in extract
    extractor_format = self.extractor.infer_extractor_format(input_path)
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/utils/extract.py", line 287, in infer_extractor_format
    if extractor.is_extractable(path, magic_number=magic_number):
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/utils/extract.py", line 84, in is_extractable
    return tarfile.is_tarfile(path)
  File "/apps/centos7/python/3.8.13_gcc9.3.0/lib/python3.8/tarfile.py", line 2471, in is_tarfile
Traceback (most recent call last):
  File "./baseline-train-translation.py", line 39, in <module>
    t = open(name)
  File "/apps/centos7/python/3.8.13_gcc9.3.0/lib/python3.8/tarfile.py", line 1603, in open
    train_data = datasets.load_dataset("wmt14", "de-en", split="train[:50%]")
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/load.py", line 1734, in load_dataset
    return func(name, "r", fileobj, **kwargs)
  File "/apps/centos7/python/3.8.13_gcc9.3.0/lib/python3.8/tarfile.py", line 1667, in gzopen
    builder_instance = load_dataset_builder(
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/load.py", line 1492, in load_dataset_builder
    fileobj = GzipFile(name, mode + "b", compresslevel, fileobj)
  File "/apps/centos7/python/3.8.13_gcc9.3.0/lib/python3.8/gzip.py", line 173, in __init__
    dataset_module = dataset_module_factory(
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/load.py", line 1216, in dataset_module_factory
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
PermissionError: [Errno 13] Permission denied: '/groups/3/gac50543/migrated_from_SFA_GPFS/matiss/cache/huggingface/datasets/downloads/792fca3fbf589fa7f59360a13cce59f3f59be07dfd8c9e0d82c17cbada1c4c39.0b6ffb30f1ac5f7e651a7facb9af03de9026bab7e033d0e0f3d9bcafe4d65d89.py'
    raise e1 from None
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/load.py", line 1187, in dataset_module_factory
Traceback (most recent call last):
  File "./baseline-train-translation.py", line 39, in <module>
    return HubDatasetModuleFactoryWithScript(
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/load.py", line 902, in get_module
    local_path = self.download_loading_script()
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/load.py", line 870, in download_loading_script
    return cached_path(file_path, download_config=download_config)
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/utils/file_utils.py", line 211, in cached_path
    train_data = datasets.load_dataset("wmt14", "de-en", split="train[:50%]")
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/load.py", line 1734, in load_dataset
    output_path = ExtractManager(cache_dir=download_config.cache_dir).extract(
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/utils/extract.py", line 42, in extract
    builder_instance = load_dataset_builder(
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/load.py", line 1492, in load_dataset_builder
    extractor_format = self.extractor.infer_extractor_format(input_path)
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/utils/extract.py", line 287, in infer_extractor_format
    if extractor.is_extractable(path, magic_number=magic_number):
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/utils/extract.py", line 84, in is_extractable
    return tarfile.is_tarfile(path)
  File "/apps/centos7/python/3.8.13_gcc9.3.0/lib/python3.8/tarfile.py", line 2471, in is_tarfile
    t = open(name)
  File "/apps/centos7/python/3.8.13_gcc9.3.0/lib/python3.8/tarfile.py", line 1603, in open
    dataset_module = dataset_module_factory(
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/load.py", line 1216, in dataset_module_factory
    return func(name, "r", fileobj, **kwargs)
  File "/apps/centos7/python/3.8.13_gcc9.3.0/lib/python3.8/tarfile.py", line 1667, in gzopen
    raise e1 from None
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/load.py", line 1187, in dataset_module_factory
Traceback (most recent call last):
  File "./baseline-train-translation.py", line 39, in <module>
    train_data = datasets.load_dataset("wmt14", "de-en", split="train[:50%]")
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/load.py", line 1734, in load_dataset
    return HubDatasetModuleFactoryWithScript(
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/load.py", line 902, in get_module
    local_path = self.download_loading_script()
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/load.py", line 870, in download_loading_script
    builder_instance = load_dataset_builder(
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/load.py", line 1492, in load_dataset_builder
    return cached_path(file_path, download_config=download_config)
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/utils/file_utils.py", line 211, in cached_path
    fileobj = GzipFile(name, mode + "b", compresslevel, fileobj)
  File "/apps/centos7/python/3.8.13_gcc9.3.0/lib/python3.8/gzip.py", line 173, in __init__
    dataset_module = dataset_module_factory(
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/load.py", line 1216, in dataset_module_factory
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
PermissionError: [Errno 13] Permission denied: '/groups/3/gac50543/migrated_from_SFA_GPFS/matiss/cache/huggingface/datasets/downloads/792fca3fbf589fa7f59360a13cce59f3f59be07dfd8c9e0d82c17cbada1c4c39.0b6ffb30f1ac5f7e651a7facb9af03de9026bab7e033d0e0f3d9bcafe4d65d89.py'
    raise e1 from None
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/load.py", line 1187, in dataset_module_factory
    return HubDatasetModuleFactoryWithScript(
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/load.py", line 902, in get_module
    local_path = self.download_loading_script()
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/load.py", line 870, in download_loading_script
    return cached_path(file_path, download_config=download_config)
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/utils/file_utils.py", line 211, in cached_path
    output_path = ExtractManager(cache_dir=download_config.cache_dir).extract(
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/utils/extract.py", line 42, in extract
    extractor_format = self.extractor.infer_extractor_format(input_path)
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/utils/extract.py", line 287, in infer_extractor_format
    if extractor.is_extractable(path, magic_number=magic_number):
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/utils/extract.py", line 84, in is_extractable
    return tarfile.is_tarfile(path)
  File "/apps/centos7/python/3.8.13_gcc9.3.0/lib/python3.8/tarfile.py", line 2471, in is_tarfile
    t = open(name)
  File "/apps/centos7/python/3.8.13_gcc9.3.0/lib/python3.8/tarfile.py", line 1603, in open
    output_path = ExtractManager(cache_dir=download_config.cache_dir).extract(
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/utils/extract.py", line 42, in extract
    extractor_format = self.extractor.infer_extractor_format(input_path)
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/utils/extract.py", line 287, in infer_extractor_format
    if extractor.is_extractable(path, magic_number=magic_number):
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/datasets/utils/extract.py", line 84, in is_extractable
    return tarfile.is_tarfile(path)
  File "/apps/centos7/python/3.8.13_gcc9.3.0/lib/python3.8/tarfile.py", line 2471, in is_tarfile
    t = open(name)
  File "/apps/centos7/python/3.8.13_gcc9.3.0/lib/python3.8/tarfile.py", line 1603, in open
    return func(name, "r", fileobj, **kwargs)
  File "/apps/centos7/python/3.8.13_gcc9.3.0/lib/python3.8/tarfile.py", line 1667, in gzopen
    return func(name, "r", fileobj, **kwargs)
  File "/apps/centos7/python/3.8.13_gcc9.3.0/lib/python3.8/tarfile.py", line 1667, in gzopen
    fileobj = GzipFile(name, mode + "b", compresslevel, fileobj)
  File "/apps/centos7/python/3.8.13_gcc9.3.0/lib/python3.8/gzip.py", line 173, in __init__
    fileobj = GzipFile(name, mode + "b", compresslevel, fileobj)
  File "/apps/centos7/python/3.8.13_gcc9.3.0/lib/python3.8/gzip.py", line 173, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
PermissionError: [Errno 13] Permission denied: '/groups/3/gac50543/migrated_from_SFA_GPFS/matiss/cache/huggingface/datasets/downloads/792fca3fbf589fa7f59360a13cce59f3f59be07dfd8c9e0d82c17cbada1c4c39.0b6ffb30f1ac5f7e651a7facb9af03de9026bab7e033d0e0f3d9bcafe4d65d89.py'
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
PermissionError: [Errno 13] Permission denied: '/groups/3/gac50543/migrated_from_SFA_GPFS/matiss/cache/huggingface/datasets/downloads/792fca3fbf589fa7f59360a13cce59f3f59be07dfd8c9e0d82c17cbada1c4c39.0b6ffb30f1ac5f7e651a7facb9af03de9026bab7e033d0e0f3d9bcafe4d65d89.py'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 240477) of binary: /home/aae15163zd/venv/pytorch/bin/python3
Traceback (most recent call last):
  File "/home/aae15163zd/venv/pytorch/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/torch/distributed/run.py", line 719, in main
    run(args)
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/aae15163zd/venv/pytorch/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
./baseline-train-translation.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-01-20_15:12:59
  host      : g0119.abci.local
  rank      : 5 (local_rank: 1)
  exitcode  : 1 (pid: 240478)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2023-01-20_15:12:59
  host      : g0119.abci.local
  rank      : 6 (local_rank: 2)
  exitcode  : 1 (pid: 240479)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2023-01-20_15:12:59
  host      : g0119.abci.local
  rank      : 7 (local_rank: 3)
  exitcode  : 1 (pid: 240480)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-01-20_15:12:59
  host      : g0119.abci.local
  rank      : 4 (local_rank: 0)
  exitcode  : 1 (pid: 240477)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[4155,1],0]
  Exit code:    1
--------------------------------------------------------------------------
